### ISSUE TITLE
transforms a string to a number when not desired

### ISSUE THREAD

**Issue by tolnai** [monken/cfn-include#35]
I have an issue with cfn-include, wheren it transforms some strings to numbers.
```
Parameters:
  MasterAccountID:
    Description: Account ID of the master account.
    Type: String
    ConstraintDescription: Must be a valid AWS Account ID without hyphens.
    AllowedPattern: '\d{12}'
    MinLength: '12'
    MaxLength: '12'
    Default: '01234567890123'
```
When running cfn-include, it transforms the above to:
```
Parameters:
  MasterAccountID:
    AllowedPattern: '\d{12}'
    ConstraintDescription: Must be a valid AWS Account ID without hyphens.
    Default: 01234567890123
    Description: Account ID of the master account.
    MaxLength: '12'
    MinLength: '12'
    Type: String
```
So it keeps MinLength and MaxLength as string, but the Default value becomes a number.
