### ISSUE TITLE
multiple includes next to each other fail

### ISSUE THREAD

**Issue by samwiseduzer** [monken/cfn-include#37]
In several files, I want to include multiple other files, but whenever I have more than one file I want to include, I get errors similar to this one. I could be using this incorrectly, but I missed anywhere in the docs that would explain why.

Resources:
  !Include { location: ./general/scalingRole.yml }
  !Include { location: ./api/main.yml }

"SyntaxError: YAMLException: bad indentation of a mapping entry at line 29, column 3" - line 29 is the second include

**Comment by monken** [comment]
Try this:

```
Resources:
  Fn::Merge:
    - !Include { location: ./general/scalingRole.yml }
    - !Include { location: ./api/main.yml }
    - Bucket:
        Type: AWS::Bucket

```
