### ISSUE TITLE
Chokes on sequence next to map

### ISSUE THREAD

**Issue by rirze** [monken/cfn-include#39]
When I try to parse a CloudFormation file with the following structure:
```yaml
            Version: 2012-10-17
            Statement:
              - Action:
                  Effect: Allow
                  Resource: '*'
                  - ec2:AttachVolume
                  - ec2:DescribeVolumes
                  - ec2:DescribeAddress
                  - ec2:AssociateAddress
```

The parser fails with this error:
```
SyntaxError: YAMLException: bad indentation of a sequence entry at line 127, column 17:
                    - ec2:AttachVolume
                    ^,SyntaxError: Unexpected token M in JSON at position 0
```

However, I know this is correct syntax because Cloudformation can run this section of YAML without issue. Maybe there is a test case not handled by the parser for this library?

**Comment by monken** [comment]
That's not a valid policy. It should read:

```yml
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - ec2:AttachVolume
                  - ec2:DescribeVolumes
                  - ec2:DescribeAddress
                  - ec2:AssociateAddress
```

I'm not sure why CloudFormation would accept this as valid YAML. You cannot mix an object with an array.
