### ISSUE TITLE
Fn::Map to support a variable for the array

### ISSUE THREAD

**Issue by danielmhair** [monken/cfn-include#48]
First off, thank you for this library. Its great!

I'm facing an issue where I am creating a reusable template in my cloudformation, and am trying to use Fn::Map in order to map a Comma Separated string into a `LaunchTemplateOverrides` Object. See the following:

Reusable cloudformation:
**node-group.yaml**
```
...
Parameters:
  ...
  NodeInstances:
    Type: CommaDelimitedList
    Description: EC2 instance types for the node instances

Resources:
  ...
  NodeGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      ...
      MixedInstancesPolicy:
        ...
        LaunchTemplate:
          LaunchTemplateSpecification:
            Version: !GetAtt NodeLaunchTemplate.LatestVersionNumber
            LaunchTemplateId: !Ref NodeLaunchTemplate

          # # Expected Cloudformation Overrides
          # Overrides:
          # - InstanceType: instance1
          # - InstanceType: instance2

          # How I converted the Overrides into a Fn::Map Function
          Overrides:
            Fn::Map:
                - !Split [ "," , !Ref NodeInstances ]
                - InstanceType: _
```

Then I assume that I would use cfn-include to compile that, and use that in another repo like so:
**multiple-node-groups.yaml**
```
AWSTemplateFormatVersion: "2010-09-09"
Description: AI Service EKS GPU and CPU NodeGroup

Resources:
  AiServiceGPUNodeGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-dev-us-east-2.s3.us-east-2.amazonaws.com/qualiti-dev-us-east-2/cluster-node-group-template.yaml
      Parameters:
        ...
        NodeInstances: !Join [',', [
          "g4dn.2xlarge",
          "p2.xlarge",
          "g4dn.4xlarge",
          "g4dn.xlarge",
          "g4dn.8xlarge",
          "inf1.2xlarge",
          "inf1.6xlarge",
        ]]

  AiServiceArgoNodeGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-dev-us-east-2.s3.us-east-2.amazonaws.com/qualiti-dev-us-east-2/cluster-node-group-template.yaml
      Parameters:
        ...
        NodeInstances: !Join [',', ["t2.medium"]]
```

I understand why this is hard to accomplish, mainly because the cfn-include generally focuses on already defined arrays for the Fn::Map, and since this is using a template for the TemplateURL, it might be harder.

I'm hoping that there is a way to do this.
