### ISSUE TITLE
Bug with new `Fn::ForEach` function

### ISSUE THREAD

**Issue by nilskch** [monken/cfn-include#57]
Hi, first of all thank you for this awesome tool! I am trying to use the new `Fn::ForEach` feature and I am running into a problem. This example stack describes the problem. I am not using `Fn::Include` here.

```yaml
# app.template.yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Parameters:
  ExampleSuffixes:
    Type: CommaDelimitedList
    Default: "1,2,3,4"
Resources:
  'Fn::ForEach::Topics':
    - Suffix
    - !Ref ExampleSuffixes
    - 'Bucket${Suffix}':
        Type: 'AWS::S3::Bucket'

Outputs:
  'Fn::ForEach::BucketOutputs':
    - Suffix
    - !Ref ExampleSuffixes
    - 'BucketName${Suffix}':
        Value: !Ref 
          'Fn::Sub': 'Bucket${Suffix}'
```

When I want to run `cfn-include -m -y app.template.yml > app.yml` I get the error:
```
(node:13643) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
SyntaxError: YAMLException: unknown tag !<!Ref> at line 23, column 1:
    
    ^,SyntaxError: Unexpected token A in JSON at position 0
make: *** [cfn-lint] Error 1
```

The problem is in the `Outputs` section. The `!Ref` part is kind of unusual and new, but I need to dynamically reference Resources that have been created using `Fn::ForEach`. I wanted to follow the examples [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-foreach-example-resource.html). `cfn-lint` works and deploying this stack works as well.

**cfn-include version:** 1.5.0

**Comment by nilskch** [comment]
It works when you use `Ref` like this.
```yaml
# ...
Outputs:
  'Fn::ForEach::BucketOutputs':
    - Suffix
    - !Ref ExampleSuffixes
    - 'BucketName${Suffix}':
        Value: 
          Ref: !Sub 'Bucket${Suffix}'
```
Closing the Issue now.
